### ISSUE TITLE
what does 'activeUponDischarge' really mean?

### ISSUE THREAD

**Issue by junmeiW** [MIT-LCP/eicu-website#42]
I found that table **'treament'** has one column **'activeUponDischarge'**,and it said that denotes whether the table'treament' was active upon discharge from the unit: True or False. If it's 'TRUE' then it means the treament was completed , whereas it's 'False' then it means the treament was cancelled?

I want to get data about people who experienced IABP , and I want to get the valid record but I don't know which is right, code is as below 
eg.
```
select  patientunitstayid ,
           treatmentid,
	   treatmentyear,
	   treatmenttime24, 
	   treatmentoffset,
	   treatmentstring,
	   activeupondischarge
from treatment 
WHERE lower(treatmentstring) similar to '%iabp%|%intro%balloon%pump%|%intraaortic%
```
and the results are like,
![image](https://user-images.githubusercontent.com/32762048/34709964-6703e1da-f554-11e7-92a4-aa86c5186dc4.png)

   
![image](https://user-images.githubusercontent.com/32762048/34709989-848e2c7e-f554-11e7-928d-8e768e434770.png)
**Are the patient's (patientunitstayid = 341780) all treaments invalid?
So, in one patient all treaments, which is valid?**

**Comment by alistairewj** [comment]
No, it doesn't mean whether the treatment was completed or not. `activeUponDischarge` indicates whether the treatment is *continuing* into the next unit on discharge from the current unit. In your case, if true, this indicates that upon discharge from the unit (presumably the ICU), the patient still has the intra-aortic balloon pump.

For some treatments (e.g. intra-aortic balloon pump removal), this flag doesn't make much intuitive sense. I'd ignore it in those cases.

**Comment by junmeiW** [comment]
Thank you very much  for your answer! It is very helpful for my research.

And I have some other questions: 

In current unit,  one patient  has multiple records about IABP and some serial records have very short intervals(e.g. 3min, 4min), does it mean this patient has experienced **multiple treaments** of IABP in the current ICU stay？ 

Is it right if I use the first IABP treament  as the real start of IABP?

And How can I identify the end time of IABP corresponding to the start?

**Comment by alistairewj** [comment]
These are off-topic from the original issue - so I'll close this and I welcome you to open a new one.

However, I honestly don't know the answer to those questions. Since there are over 200 hospitals in the dataset, the answer is usually "in some places, yes, in other places, no". Your best approach is to try to cross-reference the start/end times of IABP with something else to ensure your data is reliable. For example, if we had start/stop times of an arterial line, we could try to cross-reference it with measures of invasive blood pressure. Not sure what the equivalent check would be for IABP, but if you find it out I'm sure there are many who would be interested!
